### ISSUE TITLE
example running FlutterNfcReader.read error

### ISSUE THREAD

**Issue by wwervin72** [matteocrippa/flutter-nfc-reader#44]
example can run normally, bu when i click Read button, it throw a error. this is error track.

```
I/hwaps   (10840): JNI_OnLoad
E/MethodChannel#flutter_nfc_reader(10840): Failed to handle method call
E/MethodChannel#flutter_nfc_reader(10840): kotlin.KotlinNullPointerException
E/MethodChannel#flutter_nfc_reader(10840):      at it.matteocrippa.flutternfcreader.FlutterNfcReaderPlugin.onMethodCall(FlutterNfcReaderPlugin.kt:147)
E/MethodChannel#flutter_nfc_reader(10840):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter_nfc_reader(10840):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter_nfc_reader(10840):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#flutter_nfc_reader(10840):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_nfc_reader(10840):      at android.os.MessageQueue.next(MessageQueue.java:356)
E/MethodChannel#flutter_nfc_reader(10840):      at android.os.Looper.loop(Looper.java:138)
E/MethodChannel#flutter_nfc_reader(10840):      at android.app.ActivityThread.main(ActivityThread.java:6517)
E/MethodChannel#flutter_nfc_reader(10840):      at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_nfc_reader(10840):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/MethodChannel#flutter_nfc_reader(10840):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
E/flutter (10840): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, null, null)E/flutter (10840): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (10840): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (10840): <asynchronous suspension>
E/flutter (10840): #2      FlutterNfcReader.read (package:flutter_nfc_reader/flutter_nfc_reader.dart:69:37)
E/flutter (10840): <asynchronous suspension>
E/flutter (10840): #3      MyApp.build.<anonymous closure> (package:tet_nfc_reader/main.dart:25:36)
E/flutter (10840): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (10840): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (10840): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (10840): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (10840): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (10840): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (10840): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (10840): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (10840): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (10840): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (10840): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (10840): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (10840): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (10840): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (10840): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (10840): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (10840): #20     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (10840): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (10840):
```
what should i do, thanks.

**Comment by JERINJACOBCHERIAN** [comment]
Could you tell me how you solved this issue?
